### ISSUE TITLE
Failed install of stencila-node@0.28.4, Error: Cannot find module 'tmp'

### ISSUE THREAD

**Issue by kayakr** [stencila/node#24]
MacOS 10.13.3, node v8.9.0
09:52:04 jonathan:~ (master) $ npm install stencila-node

> sodium-native@2.1.4 install /Users/jonathan/node_modules/sodium-native
> node-gyp-build "node preinstall.js" "node postinstall.js"
> utp-native@1.6.2 install /Users/jonathan/node_modules/utp-native
> node-gyp-build
> stencila-convert@0.29.3 postinstall /Users/jonathan/node_modules/stencila-convert
> node src/helpers
> stencila-node@0.28.4 postinstall /Users/jonathan/node_modules/stencila-node
> node .copy-assets.js
npm WARN saveError ENOENT: no such file or directory, open '/Users/jonathan/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/Users/jonathan/package.json'
npm WARN jonathan No description
npm WARN jonathan No repository field.
npm WARN jonathan No README data
npm WARN jonathan No license field.

+ stencila-node@0.28.4
added 1198 packages in 55.75s
09:53:08 jonathan:~ (master) $ ./node_modules/.bin/stencila-node
module.js:538
    throw err;
    ^

Error: Cannot find module 'tmp'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/jonathan/node_modules/stencila-convert/src/Converter.js:7:13)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/jonathan/node_modules/stencila-convert/src/document/DocumentConverter.js:1:81)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/jonathan/node_modules/stencila-convert/src/document/index.js:1:89)
    at Module._compile (module.js:635:30)

**Comment by nokome** [comment]
@kayakr : thanks for the :bug: report, they're always appreciated! Can confirm this happens in a fresh Docker container too `docker run -it node bash`:

```bash
root@ac38c8f2454d:/# npm install stencila-node
<snip>

root@ac38c8f2454d:/# ./node_modules/.bin/stencila-node
module.js:557
    throw err;
    ^

Error: Cannot find module 'tmp'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)
<snip>
```

The problem arises because the `tmp` module is listed under `devDependencies` in `package.json`, when it should be under `dependencies`. An easy fix...I should be able to do it later today....unless, you'd like to submit a PR yourself - that would be even better :)

**Comment by nokome** [comment]
This particular bug should be resolved now (by removing the dependency on `stencila-convert`). You can test by installing from the master branch using `npm install stencila/node`. I have not published an updates, pending a fix for another issue on Travis (https://travis-ci.org/stencila/node/builds/354157097 -
 which frustratingly does not happen locally for me).
